# Generated by Django 6.0.5 on 2026-05-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('EMPLOYE', 'Employe'), ('RETAIL', 'Retail'), ('RISQUE', 'Risque'), ('COMITE', 'Comite'), ('ADMIN', 'Admin')], default='CLIENT', max_length=20),
        ),
    ]
