# Generated by Django 6.0.5 on 2026-06-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('EMPLOYE', 'Employe'), ('RETAIL', 'Retail'), ('COMITE', 'Comite'), ('ADMIN', 'Admin')], default='CLIENT', max_length=20),
        ),
    ]
