# Generated by Django 6.0.5 on 2026-05-18 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('situation_familiale', models.CharField(choices=[('CELIBATAIRE', 'Celibataire'), ('MARIE', 'Marie'), ('DIVORCE', 'Divorce')], max_length=20)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('type_contrat', models.CharField(max_length=50)),
                ('salaire_mensuel', models.FloatField()),
                ('anciennete_annees', models.IntegerField()),
                ('charges_mensuelles', models.FloatField(default=0)),
                ('credits_en_cours', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
