# Generated by Django 6.0.5 on 2026-06-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='autres_revenus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='habitation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='niveau_instruction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='nombre_personnes_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='secteur_activite',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
