# Generated by Django 6.0.5 on 2026-06-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_autres_revenus_client_habitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20),
        ),
    ]
