# Generated by Django 6.0.5 on 2026-06-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='validation_comite',
            field=models.BooleanField(default=False),
        ),
    ]
