# Generated by Django 6.0.5 on 2026-06-27 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('CNI', "Carte d'identité"), ('PAIE', 'Fiche de paie'), ('TRAVAIL', 'Attestation de travail'), ('JUSTIFICATIF', 'Justificatif'), ('AUTRE', 'Autre')], max_length=30)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('valide', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
