# Generated by Django 6.0.5 on 2026-05-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_regle', models.CharField(choices=[('SALAIRE', 'Salaire'), ('ANCIENNETE', 'Anciennete'), ('CONTRAT', 'Contrat'), ('ENDETTEMENT', 'Endettement'), ('SITUATION', 'Situation')], max_length=30)),
                ('valeur', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
