# Generated by Django 6.0.5 on 2026-06-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_scoringrule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoringRule',
        ),
        migrations.AlterField(
            model_name='scoring',
            name='decision',
            field=models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('A_ANALYSER', 'A analyser'), ('REFUSE', 'Refuse')], max_length=20),
        ),
    ]
