# Generated by Django 6.0.5 on 2026-06-08 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='VOITURE', on_delete=django.db.models.deletion.CASCADE, to='catalog.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, default='VOITURE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
