# Generated by Django 6.0.5 on 2026-05-18 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_bien', models.FloatField()),
                ('apport', models.FloatField(default=0)),
                ('montant_finance', models.FloatField()),
                ('marge', models.FloatField()),
                ('prix_final', models.FloatField()),
                ('duree_mois', models.IntegerField()),
                ('mensualite', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
