# Generated by Django 6.0.5 on 2026-06-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='ce_brute',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='simulation',
            name='ce_nette',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='simulation',
            name='credit_consomme',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='simulation',
            name='montant_remboursement',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='simulation',
            name='montant_total_marge',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='simulation',
            name='montant_total_tva',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='simulation',
            name='salaire_acheteur',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='simulation',
            name='salaire_co_acheteur',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='simulation',
            name='salaire_total',
            field=models.FloatField(default=0),
        ),
    ]
