# Generated by Django 6.0.5 on 2026-05-18 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('scoring', '0001_initial'),
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeFinancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ANALYSE', 'En analyse'), ('VALIDATION_EMPLOYE', 'Validation employe'), ('VALIDATION_RETAIL', 'Validation retail'), ('COMITE', 'Comite'), ('ACCEPTE', 'Accepte'), ('REFUSE', 'Refuse')], default='BROUILLON', max_length=30)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('scoring', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scoring.scoring')),
                ('simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='simulations.simulation')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(max_length=30)),
                ('nouveau_statut', models.CharField(max_length=30)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.demandefinancement')),
            ],
        ),
    ]
