# Generated by Django 6.0.5 on 2026-06-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaire_100k', models.IntegerField(default=30)),
                ('salaire_50k', models.IntegerField(default=20)),
                ('salaire_min', models.IntegerField(default=10)),
                ('mariage', models.IntegerField(default=10)),
                ('enfants', models.IntegerField(default=10)),
                ('cdi', models.IntegerField(default=25)),
                ('fonctionnaire', models.IntegerField(default=30)),
                ('anciennete', models.IntegerField(default=15)),
                ('apport', models.IntegerField(default=20)),
                ('endettement', models.IntegerField(default=20)),
                ('seuil_acceptation', models.IntegerField(default=50)),
            ],
        ),
    ]
