# Generated by Django 6.0.5 on 2026-06-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringconfig',
            name='apport',
        ),
        migrations.RemoveField(
            model_name='scoringconfig',
            name='enfants',
        ),
        migrations.RemoveField(
            model_name='scoringconfig',
            name='mariage',
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='age_jeune',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='age_moyen',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='age_senior',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='autres_revenus',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='cdd',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='habitation_locataire',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='habitation_proprietaire',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='niveau_secondaire',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='niveau_universitaire',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='personnes_charge',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='secteur_prive',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='secteur_public',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='scoringconfig',
            name='anciennete',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='scoringconfig',
            name='seuil_acceptation',
            field=models.IntegerField(default=70),
        ),
    ]
