# Generated by Django 6.0.5 on 2026-06-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='category',
            field=models.CharField(choices=[('VOITURE', 'Voiture'), ('MOTO', 'Moto'), ('ELECTROMENAGER', 'Électroménager')], default='VOITURE', max_length=20),
        ),
    ]
